echo  'This is from GIT UPdate'
echo 'After Edit'
echo 'Last Edit'
echo 'While on it'
echo 'Yeah!'
echo 'He can''t be president'
echo 'Run it again'
echo '!Run it again!'
echo '.....I am who I am...'
echo 'Fixed error'
echo 'Omenesa Muhammed ZZZZ'
